spring:
  application:
    name: backend

  datasource:
    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    locations: classpath:db/migration
    connect-retries: 20
    enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
